### ISSUE TITLE
Size of quoted text in SourceSpotlight theme is too small

### ISSUE THREAD

**Issue by acrostich** [ewlcheng/NetNewsWire-Themes#1]
I have set up NNW with the SourceSpotlight for the theme and Extra Large for the article text size. The size of text for quoted text is too small. This doesn't happen with other themes I tried so this seems to be more of a bug than a feature of this theme and hopefully will be fixed. Attached is a pic showing the different font sizes.

<img width="779" alt="image" src="https://github.com/ewlcheng/NetNewsWire-Themes/assets/1878811/fea12fbc-7886-4602-89f2-fe8a10b8eeef">

**Comment by ewlcheng** [comment]
Thanks for pointing this out, the issue has been fixed. You will have to redownload and overwrite the existing theme to get the update.
